// TODO Phase 6D: Full CRUD for violations via Hive
// TODO Phase 6D: Register ViolationData Hive adapter (generated by build_runner)

import 'package:hive_flutter/hive_flutter.dart';
import '../models/violation.dart';

class StorageService {
  static const String _violationsBox = 'violations';

  static Future<void> init() async {
    // TODO: registerAdapter(ViolationDataAdapter()) after running build_runner
    // Hive.registerAdapter(ViolationDataAdapter());
    await Hive.openBox(_violationsBox);
  }

  static Box get _box => Hive.box(_violationsBox);

  static Future<void> saveViolation(ViolationData v) async {
    await _box.put(v.id, v);
  }

  static List<ViolationData> getAllViolations() {
    return _box.values.cast<ViolationData>().toList()
      ..sort((a, b) => b.timestamp.compareTo(a.timestamp));
  }

  static ViolationData? getViolation(String id) => _box.get(id) as ViolationData?;

  static Future<void> markPaid(String id) async {
    final v = getViolation(id);
    if (v != null) {
      v.isPaid = true;
      await v.save();
    }
  }

  static Future<void> clearAll() async => await _box.clear();
}
