// lib/services/storage_service.dart
// Phase 6B: Fixed v.id → v.violationId to match ViolationData model.
// TODO Phase 6D: Full CRUD for violations via Hive
// TODO Phase 6D: Register ViolationData Hive adapter (generated by build_runner)

import 'package:hive_flutter/hive_flutter.dart';
import '../models/violation.dart';

class StorageService {
  static const String _boxName = 'violations';

  // TODO: registerAdapter(ViolationDataAdapter()) after running build_runner
  Box<ViolationData> get _box => Hive.box<ViolationData>(_boxName);

  Future<void> saveViolation(ViolationData v) async {
    await _box.put(v.violationId, v);  // fixed: was v.id
  }

  Future<List<ViolationData>> getAllViolations() async {
    return _box.values.toList()
      ..sort((a, b) => b.timestamp.compareTo(a.timestamp));
  }

  Future<void> markPaid(String violationId) async {
    final v = _box.get(violationId);
    if (v != null) {
      v.isPaid = true;
      await v.save();
    }
  }

  Future<void> clearAll() async {
    await _box.clear();
  }
}